[package]
name = "verify_directory"
version = "0.1.0"
authors = ["kyle o'neill <kyleoneill24@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data-encoding = "2.2.0"
ring = "0.16.11"